config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

 # get 'home/index'
  
=begin
  get 'homeworks/new'

  get 'homeworks/edit'

  get 'homeworks/show'
=end
=begin
  get 'subjects/new'

  get 'subjects/show'

  get 'subjects/index'
=end
  root 'home#index'
 
  get  'users/record'
  get  'users/cancel'
  get  'users/submit'
  
=begin
  get 'users/index'

  get 'users/show'
=end

devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  #devise_for :users

  resources :users do 
    resource :studies
  end
  resources :subjects 
  resources :homeworks do 
    resource :checks 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :studies
  has_many :checks
  has_many :studies_subjects, through: :studies, source: :subject
  has_many :checks_homeworks, through: :checks, source: :homework
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     '/users/record'
   end


  #def after_inactive_sign_up_path_for(resource)
    #user_path(resource)
  #end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
    def after_sign_in_path_for(resource)
      #ここでデータベースいじれる
      #user = User.find(resource.id)
      #user.user_name="aaa"
      #user.save
      user_path(resource)
    end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @subjects = Subject.all 
    @user = User.find(params[:id]) 
    @studies_subjects = @user.studies_subjects
   # @homeworks = @studies_subjects.homeworks
    @homeworks = Homework.all.where(subject_id: current_user.studies_subjects).where.not(id: current_user.checks_homeworks).where('due >= ?', Time.zone.now).order!(:due)
    #@homeworks = Homework.all.where(subject_id: current_user.studies_subjects).where.not(id: current_user.checks.homework_id) 今日より向こうのものを↑で指定
    #userモデルでhas_many through定義せずに上の感じでやったらダメだった
  end
  
  def submit
    @homeworks = Homework.all.where(id: current_user.checks_homeworks).includes(:checks).order("checks.created_at desc")
    #Model.includes(:another_model).order("another_models.name desc") 結局includesにもsつける、belongs_toでsつけてるからかと
  end 
  
  def record 
    @user = current_user 
    
    @study = Study.new
    @subjects = Subject.all.where.not(id: @user.studies_subjects).order!(:classtime)
  end
  
  def cancel 
    @subjects = Subject.all.where(id: current_user.studies_subjects).order!(:classtime)
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cancel.html.erb
<h1><%=current_user.user_name %>さんの履修状況</h1>
<% @subjects.each do |subject| %> 
  <%= subject.day%>/<%= subject.period %>
  <br>
  <%= link_to subject.name, subject_path(subject) %>&emsp;
  <%= link_to "編集する",edit_subject_path(subject) %>&emsp;
  <%= link_to "履修解除する",user_studies_path(subject.id), method: :delete%>
  <hr>
<% end %>

<%= link_to "履修登録画面へ",'/users/record' %>　
<%#= link_to "科目がない場合はこちら", new_subject_path %>

app/views/users/record.html.erb
<h1>履修登録</h1>

<%#= form_for([@user,@study], url: user_studies_path) do |f| %>
<%#= form_for([@user,@study],url: {controler: "new_user_studies", : "get" } ) do |f| %>
<%#= current_user.id %>
<% @subjects.each do |subject| %>
    
    <p>
        <%= subject.day%>曜 <%=subject.period%>コマ：&emsp;
        <%= subject.name %> <br>
        <%= link_to "この科目を履修登録する",user_studies_path(subject.id), method: :post %></p>
    <hr>
<% end %>
<%= link_to "新しい科目を作成する",new_subject_path %>

app/views/users/show.html.erb
<h1>未提出課題一覧</h1>
<p><%=link_to "新規課題作成",new_homework_path %></p>
<p>↑下の一覧に無いことを確認してから作成してください。</p>

<%# @studies_subjects.each do |subject| %>
    <hr>
    <p><%#= subject.name %></p>
<%#end %>

<% @homeworks.each do |homework| %>
  <p>
    <%= Subject.find(homework.subject_id).day %> <%= Subject.find(homework.subject_id).period %>
    <%= link_to Subject.find(homework.subject_id).name, subject_path(Subject.find(homework.subject_id)) %>
    <br>
    <%= homework.due.month %>/<%= homework.due.day%>(<%= %w(日 月 火 水 木 金 土)[homework.due.wday] %>) :
    <%= homework.name %>&emsp;<%= link_to("提出",homework_checks_path(homework.id), {method: :post, class: "btn btn-primary"}) %>&emsp;
    <%#= link_to("ログアウト", logout_path, { method: :post, data: {confirm: "ログアウトしますか？"}, class: "nav-link"}) %>
    <%= link_to "編集",edit_homework_path(homework.id) %>&emsp;
    
    <% if homework.else != ""%>
    <br> 
    <% end %>
    <%= homework.else %>
    <br>
    
  </p>
  <hr></hr>
<% end %>

app/views/users/submit.html.erb
<h1>提出済み課題一覧</h1>
<% @homeworks.each do |homework| %>
    <p>
    <%= Subject.find(homework.subject_id).day %> <%= Subject.find(homework.subject_id).period %>
    <%= link_to Subject.find(homework.subject_id).name, subject_path(Subject.find(homework.subject_id)) %>
    <br>
    <%= homework.due.month %>/<%= homework.due.day%>(<%= %w(日 月 火 水 木 金 土)[homework.due.wday] %>) :
    <%= homework.name %>&emsp;<%= link_to("未提出にする",homework_checks_path(homework.id), {method: :delete, class: "btn btn-primary"}) %>&emsp;
    <%= link_to "編集",edit_homework_path(homework.id) %>&emsp;
    
    <%= homework.else %>
    <br>
    
  </p>
  <hr></hr>
<% end %>