config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

 # get 'home/index'
  
=begin
  get 'homeworks/new'

  get 'homeworks/edit'

  get 'homeworks/show'
=end
=begin
  get 'subjects/new'

  get 'subjects/show'

  get 'subjects/index'
=end
  root 'home#index'
 
  get  'users/record'
  get  'users/cancel'
  get  'users/submit'
  
=begin
  get 'users/index'

  get 'users/show'
=end

devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  #devise_for :users

  resources :users do 
    resource :studies
  end
  resources :subjects 
  resources :homeworks do 
    resource :checks 
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/homework.rb
class Homework < ApplicationRecord
    belongs_to :subject
    has_many :checks
    validates :name, presence: true
    validates :due, presence: true
    validates :subject_id, presence: true
    #\d{4}/\d{1,2}/\d{1,2}#
    #validates :due, format: { with: /d{4}/\d{1,2}/\d{1,2}/ }
    #validates :due, numericality: { only_integer: true }
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  def new
    @homework = Homework.new
    #ソートするにはorder!、破壊的メソッドを使用
    @subjects = current_user.studies_subjects.order!(:classtime)
  end

  def edit
    @homework=Homework.find(params[:id])
    @subjects = current_user.studies_subjects.order!(:classtime)
  end

  def show
  end
  
  def create    
    @homework = Homework.new(homework_params)
    #debugger
    @homework.save 
    redirect_to user_path(current_user)
  end 
  
  def update
    @homework = Homework.find(params[:id])
    @homework.update(homework_params)
    redirect_to user_path(current_user)
  end 
  
  def destroy 
    homework = Homework.find(params[:id])
    homework.destroy
    redirect_to user_path(current_user)
  end 
  


  private
    def homework_params 
      params.require(:homework).permit(:subject_id, :name, :due, :else)
    end
    
    
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/edit.html.erb
<h1><%= @homework.name %>の編集画面</h1>
<%= link_to "戻る",user_path(current_user) %>
<%= form_for @homework do |f| %>
  <p>
    <%= f.label :subject_id,"科目名:"%>
    <%= f.collection_select(:subject_id,@subjects,:id,:name) %>
  </p>
  <P> 
    <%= f.label :name, "課題名:"%>
    <%= f.text_field :name %> 
  </P>
  <p>
    <%= f.label :due, "締め切り"%>
    <%= f.date_field :due %>
    <%#= f.text_field :due %>
  </p> 
  <p>
    <%= f.label :else, "その他"%>
    <br> 
    <%= f.text_area :else %>
  </p>
  
  <%= f.submit "送信" %>
  
<% end %>
<br>
<p>
  ↓全ユーザーに対して影響を及ぼすので注意して行ってください
  <br>
  <%= link_to "課題を消去する",homework_path(params[:id]),method: :delete %>
</p>
  

app/views/homeworks/new.html.erb
<h1>新しい課題を作成する</h1>

<%= form_for @homework do |f| %>
  <p>
    <%= f.label :subject_id,"科目名:"%>
    <%= f.collection_select(:subject_id,@subjects,:id,:name) %>
  </p>
  <P> 
    <%= f.label :name, "課題名:"%>
    <%= f.text_field :name %> 
  </P>
  <p>
    <%= f.label :due, "締め切り"%>
    <%= f.date_field :due %>
    <br>
    ※カレンダーが表示されない方は恐れ入りますが<br>
    手入力で「2020/06/05」といったように入力してください
    <br><br>
    締め切りはゆとりがあるように設定してください<br>
    例）2020/06/05 19:00までのものは2020/06/04で登録
    <br>
    <%#= f.text_field :due %>
  </p> 
  <p>
    <%= f.label :else, "その他"%>
    <br> 
    <%= f.text_area :else %>
  </p>
  <%= f.submit "送信" %>
  
<% end %>